# Generated by Django 4.2 on 2023-05-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='git_branch.levels'),
        ),
    ]
