# Generated by Django 4.2 on 2023-05-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0005_levels_image_alter_task_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='level',
        ),
    ]
