# Generated by Django 4.2 on 2023-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0007_remove_info_task_remove_infodetail_info_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
