# Generated by Django 4.2 on 2023-05-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0008_alter_levels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve', models.BooleanField(default=False)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='git_branch.levels')),
            ],
        ),
        migrations.CreateModel(
            name='InfoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_branch.info')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_branch.task'),
        ),
    ]
