# Generated by Django 4.2 on 2023-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0009_info_task_infodetail_info_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='infodetail',
            name='content',
            field=models.TextField(),
        ),
    ]
