# Generated by Django 4.2 on 2023-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0012_remotenodesolve_remotenode_nodesolve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotenodesolve',
            name='parent',
        ),
        migrations.AddField(
            model_name='remotenodesolve',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='git_branch.remotenodesolve'),
        ),
    ]
