# Generated by Django 4.2 on 2023-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0013_remove_remotenodesolve_parent_remotenodesolve_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='nodesolve',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='parent',
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='git_branch.node'),
        ),
        migrations.AddField(
            model_name='nodesolve',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='git_branch.nodesolve'),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='git_branch.remotenode'),
        ),
    ]
