# Generated by Django 4.2 on 2023-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_branch', '0014_remove_node_parent_remove_nodesolve_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nodesolve',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remotenodesolve',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
